### PR TITLE
test folder

### LINKED ISSUE #2: Is there any reason why this library build on top of BigInt?
I saw that you implement two version of the decimal proposal , one is on top of BIgInt, and another use the `decimal.js`,
what is the advantage and disadvantage between this two way?

### PR DESCRIPTION
**Pull request by munrocket**
This PR:
* fix #2 
* add bundle, because lot of online benchmarks not using esm yet

What you think about:
* expose BD(significant, exponent) constructor

### CODE REVIEW

**Comment by Yaffle** [comment]
What is a point in bundle?

**Comment by munrocket** [comment]
@Yaffle removed it, looks like you don't like it.
Sometime you have old codebase that not easy to port to esm.

**Comment by munrocket** [comment]
So I want `add, sub, div, mul` and new constructors. Because your code become a hell without short names.
This is for sure better when you migrating from BigDecimal.js to yaffle/bigdecimal.

**Comment by munrocket** [comment]
So, I need bundle because in workers it is not supported well, new constructors because it is literally imposible to use a library right now #6 and new easy API with bigdecimal.js style because math code is not trivial. Sorry for rushing, I just asking how you looking at it to make this 3 PRs.

**Comment by Yaffle** [comment]
I am agree, that API is hard to use. I was trying to follow [JSBI](https://github.com/GoogleChromeLabs/jsbi) 
`a.mul(b)` should be much shorter then `BigDecimal.multiply(a, b)`

for #6 how are you going to fix it?

**Pull request closed without merging**
